name: Project Check
on: [push]
jobs:
  build:
    name: Build, Lint, and Test project on Node ${{ matrix.node }} and ${{ matrix.os }}
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['18.x'] # '16.x',
        os: [ubuntu-latest] # macOS-latest windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node v${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install
        run: npm install

      - name: Build
        run: npm run build
